### ISSUE TITLE
Typo gitea_repository

### ISSUE THREAD

**Issue by maartenbeeckmans** [Lerentis/terraform-provider-gitea#2]
There is a small typo

The parameter is named `migration_clone_addresse` instead of `migration_clone_address`

https://github.com/Lerentis/terraform-provider-gitea/blob/main/gitea/resource_gitea_repository.go#L37

It is also wrong in some docs. Did not create a PR as this will break other users who are already using it.
If you don't want to change it for this reason, go ahead and close the issue.

**Comment by Lerentis** [comment]
good catch!

i think i can deprecate `migration_clone_addresse` in favor of `migration_clone_address` but keep both of them working for backwards compatibility. will tinker around later today

**Comment by Lerentis** [comment]
Fixed with [v0.7.3](https://github.com/Lerentis/terraform-provider-gitea/releases/tag/v0.7.3) 

this release is backwards compatible but deprecates `migration_clone_addresse` in favor of `migration_clone_address`. thanks again for the report :smiley:
