### ISSUE TITLE
gitea_repository resource fails to create repo when existing username is given

### ISSUE THREAD

**Issue by PatDyn** [Lerentis/terraform-provider-gitea#23]
**Describe the bug**  
Creating a repository with the gitea_repository resource fails
when the "username" argument receives an existing username.

**To Reproduce**  
Try to set up a new repository with an existing user. E.g.:

```terraform
resource "gitea_repository" "test_repo" {
  username = "someUser"
  name = "test_repo"
  private = false
  issue_labels = "Default"
  license      = "MIT"
  gitignores   = "Go"  
}
```

**Expected behavior**  
A repository should be created for the given user.

**Log Output**  

```bash
Error: 422 Unprocessable Entity: {"message":"org does not exist [id: 0, name: someUser]","url":"https://xxx.yyy.zzz.xy/api/swagger"}

with gitea_repository.test_repo,
on gitea_actions.tf line 15, in resource "gitea_repository" "test_repo":
15: resource "gitea_repository" "test_repo" {
```

**Additional Data**  
Important for reproducability.

- Terraform Version 1.0.8

- Operating System Kubuntu 22.04

- Provider Version 0.11.1

- Gitea Version 1.17.3

**Comment by Lerentis** [comment]
Hi @PatDyn ,

Thanks for the report. I'll have a look at it in more detail later on. In the mean time can you share the gitea version that you are using?

**Comment by PatDyn** [comment]
Sure, i just updated the issue description. :)

**Comment by PatDyn** [comment]
I might have found a clue:
In resource_gitea_repository.go, func resourceRepoCreate():

After generating the options in line 123, client.CreateOrgRepo() is called in line 137.  A client.CreateRepo() and some kind of check if the repoOwner is an org or a user may solve the issue. :)

**Comment by Lerentis** [comment]
This is a regression of the fix for https://github.com/Lerentis/terraform-provider-gitea/issues/14 :/

**Comment by Lerentis** [comment]
fixed with https://github.com/Lerentis/terraform-provider-gitea/releases/tag/v0.12.1

thanks again for the report :smiley:
