### ISSUE TITLE
Oauth2 app does not work

### ISSUE THREAD

**Issue by 76creates** [Lerentis/terraform-provider-gitea#28]
**Describe the bug**
Using `gitea_oauth2_app` just doesen't seam to work, it successfully creates the resource, but the object does not exist in Gitea somehow, its not shown in settings/applications, and I cant use id and secret for apps.

**Comment by Lerentis** [comment]
Hi @76creates
Thanks for the report. Can you provide some additional information to reproduce this? I can probably take a closer look at this over the weekend

**Comment by 76creates** [comment]
@Lerentis wanted to create a script for you and in the meantime i figured out its working as expected, must have been an issue with my gitea install in the first place, if a similar issue pops up I will post back an issue, thanks ⚡
