### ISSUE TITLE
Import existing repositories

### ISSUE THREAD

**Issue by liamshort** [Lerentis/terraform-provider-gitea#3]
# Overview

Unable to import existing repositories, getting the following error: `Error: strconv.ParseInt: parsing "MY_REPO": invalid syntax`.

# Steps to replicate

* Creating a repo as per below:

```
resource "gitea_repository" "this" {
  username     = "MY_USERNAME"
  name         = "test"
  private      = true
}
```
 
* Removing this repo from the state file
* Attempting to import the repo again `terraform import gitea_repository.this "test"`, produces the below error:

```
Error: strconv.ParseInt: parsing "test": invalid syntax
```

**Comment by Lerentis** [comment]
Hi @liamshort ,

terraform import works by referencing the ID of the repo and not the name, so assuming your repository has the ID 4 it would be: `terraform import gitea_repository.this 4`. you can look up the ID in the UI via "Administration" -> "Repositories".

That said there is another bug in the import functionality that the username is not imported, therefore the import can not really be used afterwards 😅 
I will have a look at this hopefully later today (else over the weekend)

Thanks for the report!

**Comment by liamshort** [comment]
That's magic thank you for the quick response @Lerentis . Understood that makes more sense, I've since imported the repos successfully using the IDs and now running into the `username` bug.

Cheers again!

**Comment by Lerentis** [comment]
If you don't mind i would reopen this as the import is still buggy. Will probably release a bugfix soon and update this issue accordingly with the version that contains the fix

**Comment by liamshort** [comment]
Absolutely apologies missed the bug label. Thank you 🙌

**Comment by Lerentis** [comment]
should be fixed with https://github.com/Lerentis/terraform-provider-gitea/releases/tag/v0.7.4 :smiley:

**Comment by liamshort** [comment]
Tested and it works like a charm! Thank you for the rapid fix
