### ISSUE TITLE
Add `repositories` attribute to `gitea_team` resource

### ISSUE THREAD

**Issue by yamadayutaka** [Lerentis/terraform-provider-gitea#36]
**Is your feature request related to a problem? Please describe.**

Missing attribute to specify repositories when creating team with `include_all_repositories = false`.

**Describe the solution you'd like**

I want an attribute that specifies the target repository as follows.

```tf
resource "gitea_team" "test_team_restricted" {
  name                     = "Restricted Devs"
  organisation             = gitea_org.test_org.name
  description              = "Restricted Devs of Test Org"
  permission               = "write"
  members                  = [gitea_user.test.username]
  include_all_repositories = false
  repositories             = [gitea_repository.test.name]
}
```

**Describe alternatives you've considered**

None.

**Additional context**

I will create a pull request for this issue.

**Comment by Lerentis** [comment]
Released as [v0.13.0](https://github.com/Lerentis/terraform-provider-gitea/releases/tag/v0.13.0) . Thanks again for raising this and implementing this feature at the same time 💯
