### ISSUE TITLE
 Allow migration of non-mirrored repositories as well

### ISSUE THREAD

**Issue by ultimania** [Lerentis/terraform-provider-gitea#39]
**Is your feature request related to a problem? Please describe.**
I want to migrate a clone repository from another Git server, but I can only migrate a mirror repository, and when I try to migrate with `mirror=false` , an empty repository is created.

**Describe the solution you'd like**
I want to be able to migrate even if `mirror=false`  is specified as follows.

```hcl
resource "gitea_repository" "clone" {
  username                     = "lerentis"
  name                         = "terraform-provider-gitea-clone"
  description                  = "Clone of Terraform Provider"
  mirror                       = false
  migration_clone_address      = "https://git.uploadfilter24.eu/lerentis/terraform-provider-gitea.git"
  migration_service            = "gitea"
  migration_service_auth_token = var.gitea_clone_token
}
```

**Describe alternatives you've considered**
None

**Additional context**
I will create a pull request for this issue.

**Comment by Lerentis** [comment]
Released as [v0.14.0](https://github.com/Lerentis/terraform-provider-gitea/releases/tag/v0.14.0).
Thanks again for picking this up
