### ISSUE TITLE
Token is required during second execution

### ISSUE THREAD

**Issue by dotdiego** [Lerentis/terraform-provider-gitea#5]
I'm using the latest provider version and when running it first time with a user:password it works perfectly.
However when I retry to plan or destroy something I hit this error

```
Error: token is required
```

Should I store the token somehow after the first run in my variables ? Or is it a bug and user:password connection should be available at all times ?

**Comment by Lerentis** [comment]
Hi @dotdiego ,

this sounds not like the intended behaviour. can you provide something for me to reproduce this? token and basic auth are mutually exclusive but nothing should stop you from sticking with one or the other. a bit more information about your environment would also help to reproduce this

**Comment by dotdiego** [comment]
```
variable "gitea_url" {
  type = string
}

provider "gitea" {
  # Configuration options
  base_url = var.gitea_url   # optionally use GITEA_BASE_URL env var
  username    = "username"
  password    = "password"
}

resource "gitea_org" "homelab" {
  name = "homelab"
}

resource "gitea_repository" "mirror" {
  username                     = "alpha"
  name                         = "homelab-nomad-jobs"
  description                  = "Mirror of homelab-nomad-jobs"
  mirror                       = true
  migration_clone_addresse     = "https://github.com/dotdiego/homelab-nomad-jobs"
  migration_service            = "github"
  migration_service_auth_token = var.gitea_mirror_token
}

resource "gitea_oauth2_app" "drone-app" {
  name          = "drone"
  redirect_uris = ["http://drone.local/login"]
}

```

I'm using the provider this way.
One fact to note is that before that step i'm deploying Gitea through a nomad job

```
resource "nomad_job" "gitea" {
  jobspec = file("${path.module}/nomad/gitea.nomad")

  hcl2 {
    enabled = true
  }
}
```

Do you need more informations to reproduce ?

**Comment by Lerentis** [comment]
Hmm i can not reproduce this.
i created a new gitea instance with the [docker-compose file](https://github.com/Lerentis/terraform-provider-gitea/blob/main/scripts/docker-compose.yaml) in this repo and adapted your code with missing information like this:

```hcl
variable "gitea_url" {
  type = string
  default = "http://localhost:3000"
}

variable "gitea_password" {
  type = string
}

variable "github_token" {
  type = string
}

terraform {
  required_providers {
    gitea = {
      source = "Lerentis/gitea"
      version = "0.8.0"
    }
  }
}

provider "gitea" {
  # Configuration options
  base_url    = var.gitea_url   # optionally use GITEA_BASE_URL env var
  username    = "lerentis"
  password    = var.gitea_password
}

resource "gitea_org" "homelab" {
  name = "homelab"
}

resource "gitea_repository" "mirror" {
  username                     = "lerentis"
  name                         = "homelab-nomad-jobs"
  description                  = "Mirror of homelab-nomad-jobs"
  mirror                       = true
  migration_clone_addresse     = "https://github.com/dotdiego/homelab-nomad-jobs.git"
  migration_service            = "github"
  migration_service_auth_token = var.github_token
}

resource "gitea_oauth2_app" "drone-app" {
  name          = "drone"
  redirect_uris = ["http://drone.local/login"]
}
```

This repeatedly works as intended. i also double checked and the token is flagged as optional and as you can see [here](https://github.com/Lerentis/terraform-provider-gitea/blob/main/gitea/provider.go#L18) it is optional. 

can you reproduce this is a minimal environment, so taking nomad out of the picture to reduce the scope?

**Comment by dotdiego** [comment]
Hmmm I can't exactly pinpoint the issue.
I had it once but deploying the default user in gitea resulting in this. So I think it might just be that the error is not explicit.
And another time when running terraform while gitea was still deploying (resulting in error to connect to the gitea_url). 
Then running it again once gitea was deployed.

I split up my modules and added a verification for gitea to be reachable to avoid getting those errors again.
