### ISSUE TITLE
Implement forks

### ISSUE THREAD

**Issue by juddowilcox** [Lerentis/terraform-provider-gitea#6]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to use a gitea_fork resource.

**Describe alternatives you've considered**
I've considered writing a terraform provider that wraps curl, a gitea_repository with a provisioner, etc. I have considered other non-terraform options including kubernetes operator, crossplane provider, etc.

**Additional context**
Specifically, I need a crossplane provider to provide a fork resource for gitea. I have already generated a working provider via terrajet using Lerentis/gitea. Now I need the fork resource.

**Comment by juddowilcox** [comment]
I am willing to try to implement this or to to test it if someone else implements it.

**Comment by Lerentis** [comment]
Hi @juddowilcox

I am not sure I understand what you mean here. Usually a fork is something that you do and not something that you do using a terraform run. Of cause I don't know your use case, so if you want to implement this resource type, I am happy about a contribution

**Comment by juddowilcox** [comment]
Using crossplane I have to automate deployment of gitea instances into eks
in aws. Each instance must be automatically configured with mirrors (of
repos elsewhere) and forks of those mirrors. I generate the crossplane
provider from your terraform provider.

I am not a go developer but I'll give it a try. Thank you for your work on
