### ISSUE TITLE
Implement tokens

### ISSUE THREAD

**Issue by juddowilcox** [Lerentis/terraform-provider-gitea#7]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Would like a "token" resource that implements

- post /users/{username}/tokens
- get /users/{username}/tokens
- delete /users/{username}/tokens/{token}

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by juddowilcox** [comment]
I am willing to try to implement this or to test it if someone else implements it. I am unsure how to do this since go-sdk/gitea doesn't seem to support it. ATM I'm thinking of implementing as, basically, a resource wrapper around the necessary curl commands.

**Comment by Lerentis** [comment]
implemented via c72fcb3a49cdc2d64e17d4b1361d010efb3f9f7c and released in [v0.10.0](https://github.com/Lerentis/terraform-provider-gitea/releases/tag/v0.10.0)
